### ISSUE TITLE
有时会异常占用cpu

### ISSUE THREAD

**Issue by lurve1314** [410154425/AdGuardHome_magisk#10]
用的是kernelsu0.8.1,模式一

**Comment by lurve1314** [comment]
![Screenshot_2024-03-01-14-17-02-532_com omarea vtools-edit](https://github.com/410154425/AdGuardHome_magisk/assets/129316709/41a9c049-b9f5-46a4-aa5e-3747712e9a8e)
![Screenshot_2024-03-01-14-17-19-415_com omarea vtools-edit](https://github.com/410154425/AdGuardHome_magisk/assets/129316709/a4f60ada-53b8-4ce6-9e8e-67def39e987f)

**Comment by 3469184525** [comment]
上游原因
