### ISSUE TITLE
关于重构本模块的一些问题

### ISSUE THREAD

**Issue by BlueFunny19** [410154425/AdGuardHome_magisk#12]
我想要对您的模块进行一下完整的重构，对一些已有的问题进行修复，并增添一些新的功能，但是我没有看到此模块的开源许可证，我想问一下我能否将重构后的模块进行开源发布？

**Comment by TeaqariaWTF** [comment]
> 我想要对您的模块进行一下完整的重构，对一些已有的问题进行修复，并增添一些新的功能，但是我没有看到此模块的开源许可证，我想问一下我能否将重构后的模块进行开源发布？

Can you do that?
I guess the developer is not very interested in the project

**Comment by TG-Twilight** [comment]
I'm very happy to see someone is planning to refactor this module.

**Comment by PDxtXHd** [comment]
作者长期活跃的平台是酷安，主页是 http://www.coolapk.com/u/1373784 你通过酷安联系上他的可能性更高
![image](https://github.com/user-attachments/assets/1a3cf109-ae06-47d8-9da2-ef2106aaab7e)

**Comment by BlueFunny19** [comment]
hmmmm, 我本人现在已经很长一段时间没有上过酷安了, 因为一些众所周知的问题...
外加我目前学业比较繁重, 等之后我相对清闲一些了我再去联系一下他吧
不过目前我的打算是完全重新写一个模块了, 所以之后可能会重新开一个库这样()
