### ISSUE TITLE
Clash for Android致使模块失效的解决方案

### ISSUE THREAD

**Issue by sun2ot** [410154425/AdGuardHome_magisk#2]
您好，我已阅读配置文件且知悉Clash默认配置下会导致模块过滤失效，请问有没有什么方案可以解决该情况呢？除了更换代理软件外。

盼复，谢谢。

**Comment by 410154425** [comment]
没有，不想换软件，那就用Clash for Magisk

**Comment by twoone-3** [comment]
可以将clash for android设置-覆写-dns策略改为不修改，这样就能屏蔽广告了

**Comment by wzmtgggg** [comment]
> 没有，不想换软件，那就用Clash for Magisk

请问如果换软件用什么呢
