### ISSUE TITLE
页端控制面板安全问题：未限制仅允许localhost连接

### ISSUE THREAD

**Issue by yqs112358** [410154425/AdGuardHome_magisk#6]
如题，同一Wifi下所有设备都可以通过`http://<手机IP>:3000`访问控制面板，加上默认的root/root弱密码，相当危险
如图是电脑连接进入控制面板
![image](https://github.com/410154425/AdGuardHome_magisk/assets/37969157/0e0d860d-0847-4c42-9d9e-1959a7078fb0)

**Comment by 410154425** [comment]
可以通过AdGuardHome.yaml文件修改用户名，重启生效。

**Comment by yqs112358** [comment]
OK，已修改。
另外试了一下，上面的http监听address可以改成127.0.0.1，这样就只有本机能访问页端控制台了。
